### ISSUE TITLE
Performance & Topics Collection - Step 1 (Minutes Seeding Tool)

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#172]
We see performance issues on long-living meeting series in the finalize step. 

First we want to understand, why this is so... (maybe improve the existing performance script?)

Currently we think an own "Topic Collection" might help. So consider this while searching for a solution of the performace bottleneck.

**Comment by felixble** [comment]
In the first step we provided a minutes seeding tool (see 136c898acd625622534e51b58ddc7a84d7b6f4a6). This tool allows to create minutes with dummy data automatically. It can be used for inserting dummy data which is helpful for analysing the performance of 4minitz.

We will close this issue because the next step is described by issue #216.
