### ISSUE TITLE
Improve UX on "Edit old Details"

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#234]
As a user I want cloned details if I edit details from previous minutes in the current minutes because I do not want to lose information in the "topic all time history".

If details (with an older time stamp) are available in the current minute and user triggers "edit details":
1.) Make a clone of the details
2.) Give the clone a fresh time stamp
3.) Open markdown editor on the clone

- [ ] It is not possible to change details of older minutes
- [ ] If the details have been added in the current minute (either by clone or by "Add details") they can be edited without cloning
- [ ] Old or new/cloned details can be deleted

**Comment by iCatCat** [comment]
3d

**Comment by iCatCat** [comment]
A current user story was changed to following:
As a user I want to see a current timestamp if I edit details from previous minutes in the current minutes 
- [ ]  if user edits details: update a timestamp to a fresh one


Make some changes to the details-scheme:
- [ ]  create a new _id for all details. A possible approach would be: 
1. iterate through all Minutes in a MinutesSeries from the oldest to the newest one
2. assign a random _id to all details in a first Minute 
3. if there’s the same Topic with same Items in the second Minute: compare details-text and assign an new _id if texts are different. Otherwise: same _id
- [ ]  create a new „createdInMinute“-Attribute for all details
- [ ] a DB-Migration is needed (use the following script for tests: tests/performance/insertMeetingSeries.js)

**Comment by felixble** [comment]
With the mentioned script you can easily insert fake meeting minutes for testing purposes. The usage of the script is described in our developer doc in the section [Database Seeding](https://github.com/4minitz/4minitz/blob/develop/doc/developer/developermanual.md#database-seeding)

**Comment by felixble** [comment]
Please also consider the following aspect:
- [x] if the user leaves the details editor without changing its content do not update the timestamp
