### ISSUE TITLE
Improve performance for Topic/Items-Tab

### ISSUE THREAD

**Issue by felixble** [4minitz/4minitz#239]
Displaying and filtering the elements of the topic and items tab takes way too long for large meeting series. Rendering the Topic-Tab with 8 Topics containing more than 200 items takes about 6 seconds!

A performance analysis showed that the rendering of the blaze template engine it our bottleneck.

**Comment by migerh** [comment]
The cause appears to be a combination of blaze/tracker computations and material design.

![image](https://cloud.githubusercontent.com/assets/368715/25734029/45db1e92-315f-11e7-946c-27697cc66dc3.png)

**Comment by migerh** [comment]
* We add arrive.js handlers that we don't remove. This causes the second big block "Run Microtasks" to get bigger on every recreation of the topics list template
* The first block is just blaze being terribly slow

Some ideas on how to improve the performance:
* Reduce arrive.js usage. We won't be able to remove everything since the bootstrap material design relies on it. But maybe we can reduce our own usages. To do this we have to somehow be aware when certain nodes are added to the DOM reactively. React has a react component method called `componentIsMounted` or something like that. How can we detect that a DOM node is added that needs to be transformed by e.g. the bootstrap-datetime-picker?
* Reduce the number of topics shown be either pagination or infinite scrolls. For the first several packages exist that should make this rather easy. For the second we have to make sure that only a certain amount of info items is loaded dynamically. So we can't just load one topic at a time, because if one topic has 300 infoitems this one needs too long as well. Also, with infinite scrolling we have to find a better place for the quick help box.

**Comment by migerh** [comment]
Performance has been improved.
