### ISSUE TITLE
Re-Verification on profile mail change

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#275]
If admin has activated mail verification and user has verified his initial mail address, it may be surprising for the admin that the user can change the mail adress via user profile editor without a re-verfication of the new address.

- [x] If mailverification feature is turned on & user changes mail address via profile editor, show warning message: " Warning: You are about to change your verified mail address. You will be signed out and need to verify your new mail address before you can continue" [Cancel | Sign Off & Re-Verify] 
- [x] On "Cancel" allow to change the content of the profile editor
- [x] On "Sign Off & Re-Verify", set new mail address to "verified == false", send verification mail to new mail address and perform a "forced sign off" for the user. Use https://docs.meteor.com/api/accounts.html#Meteor-logoutOtherClients for this!

**Comment by RobNeXX** [comment]
"On "Cancel" allow to change the content of the profile editor":
I don't think we should save changes on cancel event.
A user will be confused when the changes will be saved on "cancel".
I would suggest:
- Rename "cancel" to "Save changes without email" (or something that sounds better)
- Only save changes on "sign off & reverify"

**Comment by felixble** [comment]
@RobNeXX I think what @derwok meant with "On 'Cancel' allow to change the content of the profile editor" was that canceling the warning message does not close the profile editor. Instead the profile editor will stay open and the user can edit his profile. At this point I think it would make sense if the content of the email address field should be reverted.

So if I change both my long name as well as my email address I can cancel the dialog (because I do not want to re-verify my address) and click save again which in case only changes my long name.

**Comment by RobNeXX** [comment]
@felixble I think this use case is not common. When a user wants to change his mail i think there will be no reconsidering only because of the warning dialog

**Comment by felixble** [comment]
@RobNeXX with this feature we want to forbid changing the email without validating the new one. So if he does not want to send a new validation mail he cannot change his email address. Instead of just proceeding with our workflow (do a logout and send an validation mail for the new address) we present him a warning. Then the user can decide whether he wants to continue or cancel the operation.

It the user does not change his mind he still wants to use a new email address. Indeed, this is only possible if he continues with "Sign Off & Re-Verify".

**Comment by felixble** [comment]
@RobNeXX I think I misunderstood your suggestion. I thought the button "Save changes without email" should save all changes without sending a validation mail. Instead it should save all changes and skip the email address.

This is a nice idea. However, I think - as you said before - this is not common. So we should concentrate on the common use cases: `Cancel` should close the warning and return to the dialog.
