### ISSUE TITLE
Indicate participants of the minimum quorum for the meeting

### ISSUE THREAD

**Issue by AtJano** [4minitz/4minitz#389]

**Comment by derwok** [comment]
Hi @AtJano 
Great that you are interested in 4Minitz.
Nevertheless your enhacement idea seems a little bit blurry to me.
Could you work out some details? What do you want to achive?
Maybe you can formulate one or more user stories (in form of the user story template)?

**Comment by AtJano** [comment]
The quorum is the minimum number of members who must be present at a meeting to decide/vote issues/business.  No motions or votes should occur unless there is a quorum.  As a result, if quorum is lost the meeting or the debate of the item stops.

**Comment by derwok** [comment]
We understand your idea better now. Thanks for your suggestion. Nevertheless dicussion would be needed how to integrate this in the UI without cluttering the interface for users that don't want this feature.
So, we do not plan this enhancement in the near future.
We will keep it in the list for a few more month to see, if a pull request / code contribution shows up. Otherwise we will close it as "won't fix".

**Comment by derwok** [comment]
No upvotes, no pull requests, no "me too".
Will close this issue as "won't fix"
