### ISSUE TITLE
Conflicts of interest

### ISSUE THREAD

**Issue by AtJano** [4minitz/4minitz#390]
If a proposed decision of the participant is concerned with an actual or proposed transaction or arrangement with the organization in which a participant is interested, that participant is not to be counted in the decision-making process for quorum or voting purposes.

**Comment by derwok** [comment]
Hi @AtJano 
Great that you are interested in 4Minitz.
Nevertheless your enhacement idea seems a little bit blurry to me.
Could you work out some details? What do you want to achive?
Maybe you can formulate one or more user stories (in form of the user story template)?
Maybe add a precise example with "Alice" and "Bob"?

**Comment by AtJano** [comment]
Let's say that in the meeting a item is about the promotion/process/conduct of Mr. Smith, because there is conflitct of interest he has to leave the room/meeting for this item (and can't vote), but he may return for the other items.

**Comment by derwok** [comment]
We understand your idea better now. Thanks for your suggestion. Nevertheless dicussion would be needed how to integrate this in the UI without cluttering the interface for users that don't want this feature.
So, we do not plan this enhancement in the near future.
We will keep it in the list for a few more month to see, if a pull request / code contribution shows up. Otherwise we will close it as "won't fix".

**Comment by derwok** [comment]
No upvotes, no pull requests, no "me too".
Will close this issue as "won't fix"
