### ISSUE TITLE
Record in minutes the entrance of a participant/member after the meeting start

### ISSUE THREAD

**Issue by AtJano** [4minitz/4minitz#391]
Record in minutes whem:

1) A participant/member enter after the meeting start
2) In the case of conflicts of interest record that the participand Y leave or other the room for that reason (or other accepeted in rules).

**Comment by derwok** [comment]
Hi @AtJano 
Great that you are interested in 4Minitz.
Nevertheless your enhacement idea seems a little bit blurry to me.
Could you work out some details?
Why is it not possible to note these things in the details field of a decision info item?
Where in the current GUI you suggest to put this info?

**Comment by AtJano** [comment]
1) For instance a meeting starts after getting quorum, and stops if someone leave and you louse quorum. v.g. "The meeting start whit attendance of mr. A, B, Dr. C at 10 p.m. ..." (Introduction text)

2) During meeting a participant enter or arrives, that must be record as an observation/note v.g. "At this point Mr. Smith enter/leave the room/meeting" and them proceed to decision info (Mr. Smith can't vote because he was away of the debate item (not there or conflict of interest)

**Comment by derwok** [comment]
We understand your idea better now. Thanks for your suggestion. Nevertheless dicussion would be needed how to integrate this in the UI without cluttering the interface for users that don't want this feature.
So, we do not plan this enhancement in the near future.
We will keep it in the list for a few more month to see, if a pull request / code contribution shows up. Otherwise we will close it as "won't fix".

**Comment by derwok** [comment]
No upvotes, no pull requests, no "me too".
Will close this issue as "won't fix"
