### ISSUE TITLE
Use remote mongo server 

### ISSUE THREAD

**Issue by no7ren** [4minitz/4minitz#393]
Hi,
I try to use the existing mongo server by specifying the environmental variable in the docker run command: -e MONGO_URL=mongodb://4min:pwd@remoteserver:27017/4minutes. The server is running but  I get the following message on the page: Error Unfortunately the minute is not linked to its parent series correctly - please contact your system administrator.

I checked with my remote mongo server and nothing were inserted there. And I also found all the collections are inserted under database admin. Can I use another database instead of admin locally?  Is it possible to use the remote mongo server?

**Comment by derwok** [comment]
Thankx for pointing this out. You are right currently the docker image does not allow to overwrite the Mongo DB URL. 

The root cause for your issue is in line 73 of the docker run script here:
https://github.com/4minitz/4minitz/blob/5f62d6292198acca96f4cd786335f6c2883463a1/.docker/4minitz.sh#L73
We set the MONGO_URL environment variable regradless if it was set from outside or not.
No good style... We will fix your issue with a future release.

In the meanttime you may perform the following 

**Workaround:**
1. Launch your docker container without the "-e MONGO_URL" parameter.
1. When the container is up-and-running you will see a message like this in the shell: 
`To log in to your 4minitz server container:  docker exec -it XXXXXXXX /bin/bash`
(With a different container ID of course!). Copy & paste this line to a fresh shell.
1. When you have a shell inside the container do: `nano 4minitz.sh` 
1. Search for line number 73 where MONGU_URL is set and insert your preferred MONGO_URL
1. Press "Ctrl+O" "Enter" "Ctrl+X" to save and quit
1. `exit` from shell
1. Then "Ctrl+C" & restart your 4Minitz container

We would be happy to hear, if the workaround works for you.

**Comment by derwok** [comment]
One important thing to remember when using "docker -e MONGO_URL":
Docker creates a so called container network. So, per default its not possible to connect from a container to the host or to an arbitrary server that the host sees. Please refer to the docker `--network` switch doc for more info.

To make sure your 4Minitz container can see the external MongoDB server outside of the container please perform:
`docker run -it --rm -v $(pwd)/4minitz_storage:/4minitz_storage -p 3100:3333 4minitz/4minitz /bin/bash` 

Important here: /bin/bash at the end of the line will prevent 4Minitz from launching and give you a container shell instead. 

Then do `ping YOUR-MONOGO-IP` to check if container can connect to your MongoDB server.

**Comment by derwok** [comment]
We implemented MONGO_URL preservation into our docker deployment. But currently only on our develop branch. The image is just pushed to docker hub. 

```
docker run -e MONGO_URL=.... -it --rm -v $(pwd)/4minitz_storage:/4minitz_storage -p 3100:3333 4minitz/4minitz:develop
``` 

You should see in the console the MONGO_URL value the container uses.
We also added some hints to our admin doc - see here: 
https://github.com/4minitz/4minitz/blob/develop/doc/admin/adminguide.md#external-mongodb-server-with-your-4minitz-docker-container

Especially: please ensure your 4Minitz container has its network configured in a way it can see/ping/access the external MongoDB server...

If you like, could you give it a try and report back if it works?

**Comment by no7ren** [comment]
Great work! I just tested it and it works like a charm.
