### ISSUE TITLE
Line Break for „Global Note“

### ISSUE THREAD

**Issue by fd0cwp** [4minitz/4minitz#429]
Hi WOK,

As already discussed, it would be nice if the „Global Note“ field (which is sticky now :-)) would support line breaks because we would like to note a longer text as some guideline for the meeting. 
Even if the long text is completely visible in the email, it would be good so see the text also completely in the minutes so it is easier to update it.

Maybe after this change it would be reasonable to be able to collapse the field like the "Participants" list because it might "waste" a lot of height?

Best regards, Christoph

**Comment by andyshilton** [comment]
I must second this. Love the system, but this is one of the issues I've faced. I use the Global Notes to send out instructions of what to prepare for the meeting and what I need sent to me before hand. Being able to use Markup and mutli lines on the global notes would be a huge help :)

**Comment by derwok** [comment]
As a moderator I want to have multi line "Global Note" so that I can distribute even more complex meeting rules and notes.

Acceptance Criteria:
1. Field should be initially 2 lines in height
1. Pressing ENTER in this field will add a line
1. If user adds more lines, the hight should increase
1. Line breaks should be preserved in: browser, eMail and generated PDFs, finalized meetings
1. TAB should allow to leave field. Latests in this case changes shall be stored to database (and be propagated to other connected users)

Hint: The "Add Info Item" dialog has a "Details" multi line text area that grows automatically in height.
