### ISSUE TITLE
[v1.5.0] Migration#23 corrupts existing infoItems in minutes collection

### ISSUE THREAD

**Issue by derwok** [4minitz/4minitz#437]
Unfortunately we have a bug in v1.5.0 which corrupts existing infoItems in the minutes collection.

before migration#23:
![grafik](https://user-images.githubusercontent.com/4393698/38835559-d8dafb04-41cb-11e8-9319-33555f4e763a.png)

after migration#23
![grafik](https://user-images.githubusercontent.com/4393698/38835594-ee510b86-41cb-11e8-9f08-c9ea761b2a13.png)

I pushed a hotfix on master & develop & docker image (v1.5.1 == latest) which simply skips migration step 23. But this will only help people that have not yet migrated...

For people that have migrated, we will provide a fix soon.
Seems the data is still there - not lost! - but format of data has changed so that 4Minitz currently can't use it.

Stay tuned. And: apologies!

**Comment by migerh** [comment]
Root cause is not `Schema.find()` apparently sometimes returns an astronomy class for subschemas. A fix for migration_23 is here: 86e24e8c475cd44f3

Todo:
- [ ] Fix migration_23 unit tests
- [ ] Provide migration_24 to fix the database for users that already migrated. Check if it's an astronomy EJSON value for every infoitem in the minutes collection and use EJSON.parse on it to extract the document.
