### ISSUE TITLE
Malformed account verification link

### ISSUE THREAD

**Issue by fishishuntingsharks** [4minitz/4minitz#442]
Hi,

I registered an account for the 4minitz demo server.

The activation link I got was 

> https://demo.4minitz.com/#/verify-email/CANi403EVUpcy0VEG...

and the account was not verified when clicking on it.

Removing the "/#" solved it for me, so there might be an issue in the creation of the verification link.

Best regards

**Comment by migerh** [comment]
Thanks for letting us know.

I think it may be more of a routing issue. The link is generated by meteor itself or a core meteor package so that link should be ok. But maybe our client side routing is getting in the way here.

@derwok @felixble 
Could this be the root cause? Do we need to add a /#/ there? https://github.com/4minitz/4minitz/blob/develop/client/router.js#L34

Any way to check this on a local install without a mail server attached?

**Comment by derwok** [comment]
It seems we have code in place to strip the odd "#/" from the URL like suggested [here](https://themeteorchef.com/tutorials/sign-up-with-email-verification#tmc-customizing-the-verification-template)

We have this code here: 
https://github.com/4minitz/4minitz/blob/df6c6af4f8603f6eca78c74157d3edc697e23d6b/imports/config/EMailTemplates.js#L14

I'm pretty sure this code was called in the past.
Currently is seems this code is not called anymore, as the EMail sent has this text:
``` 
Hello Wolfram Wok2,
To verify your account email, simply click the link below.
http://localhost:3100/#/verify-email/ocqrKCr8l1Rk3a3QUdVzl1Jbjhc7BlUexuP9q44W07W
Thanks.
``` 
which is the default libary text.

**Comment by derwok** [comment]
So, we have to find out why our accounts config code is not called anymore..

**Comment by derwok** [comment]
Ah! Before configuring the AccountsPackage we check if email is enabled. We do this via `GlobalSettings.isEMailDeliveryEnabled()` - but GlobalSettings are not initialized at this point in time.
As our non-reachable code is serverside, we may happily use `Meteor.settings.email.enableMailDelivery` instead
