### ISSUE TITLE
Admins cannot alter accounts

### ISSUE THREAD

**Issue by andyshilton** [4minitz/4minitz#446]
We recently had a situation where a new user was added, but accidentally had the wrong email address set up (a typo). However, the user couldn't use the "forgot my password link" because the email was wrong, and the admin currently has no was to edit the account.

Would it be possible to add an "edit accounts" for admins so they can help staff reset passwords and change emails etc.

**Comment by derwok** [comment]
Oh! OK. Yes - it seems we overlooked this trap.
Sorry!

What we can offer is that on admin page (where all users are listed) the admin may trigger the "Edit Profile" dialog of an arbitrary "Standard" (Non-LDAP) user. Then admin may change mail address or user's long name.
If mail address changes, we will "auto verify" the mail address, as we trust the admin. So no verification mail will be sent.

Nevertheless (for the time being): admin will not be able to change a user's password this way because
* The current password dialog requires to enter the old password (which the admin does not know)
* The password dialog is separate from the edit profile dialog (for hiostorical reasons).

**Comment by derwok** [comment]
OK. I added this feature to our develop branch and pushed an "unstable" docker image to docker hub.
On admin view user list you have now a little pen icon to trigger the user profile editor:
![grafik](https://user-images.githubusercontent.com/4393698/41315959-4a937c84-6e91-11e8-916f-841789deaba6.png)

If you want this functionality immediately and you are using the docker deployment, consider to run this command:

```
docker run -it --rm -v $(pwd)/4minitz_storage:/4minitz_storage -p 3100:3333 4minitz/4minitz:develop
``` 
Hope, it works for you.

**Comment by andyshilton** [comment]
@derwok Thanks. Not a complaint at all mate, just trying to help with feedback as we love 4minitz. Makes life with meetings so much easier. Out of interest though, is there a particular schedule for releases? I'm not overly keen to switch to unstable versions just for one feature and would rather wait a known period of time.

**Comment by derwok** [comment]
Hi @andyshilton, thanks for your feedback. Good to hear, you like 4Minitz (don't forget to "Star" our project).
Currently there is no release shedule. As this is a side project we tend to work in "burst mode" (Like a few weeks silence, then a free weekend allows for some issue tackeling and enhancements).
Between the last two releases was like 6 month. I hope this time we will be quicker.  ;-)
Let's say: Goal is to push a new release before summer vacation. Means: before August.
Dont blame us if this plan does not work out...  ;-)

**Comment by andyshilton** [comment]
@derwok  Starred!!
Thanks for the feedback. Great to know. Totally understand ref dates, but good to have an idea of how you are working. We'll keep feeding back on things we find to help too. Thanks.
