### ISSUE TITLE
Attachments link incorrect.

### ISSUE THREAD

**Issue by mechanysm** [4minitz/4minitz#453]
Hi There,

We are experiencing an issue where when documents are uploaded it appears to work correctly but then when users go to download the document (pdf) they get a "File Not Found :(" page.

This appears to me like its the links as this is an example link
`http://4minitz:3100/cdn/storage/AttachmentsCollection/hEXRrYKaDPJCBkgWc/original/hEXRrYKaDPJCBkgWc.pdf?download=true`
and this is the path to where the file ends up.
`../4minitz_storage/attachments/PEJGeoHtnkvw6m9EN/hEXRrYKaDPJCBkgWc.pdf`

Maybe i'm missing something here but I can't seem to get it working.
My path in the settings JSON is the default.
`"storagePath": "4minitz_storage/attachments",`

Not sure whats going on maybe I have configured something incorrectly?

**Comment by derwok** [comment]
Hi Terry,
nice to hear from you...
First, please make sure you run the latest 4Minitz (1.5.2).
The I want to state, we have quite a few instances of 4Minitz running where the attachment download works quite well - so I think we are facing some configuration/browser topic here.

Could you quickly confirm that the File Not Found message 
- appears inside the browser window as plain text (not a pop up or nice formattated message!)
- Is something like this:  `File not found :(` (with a frowny).

If this is so, then this is the message from the Meteor:Files package middle ware we are using.
When this shows this error - at least in the past - it had one of two reasons:
1. Meteor:Files works with its own cookie. This cockie worked fine on all modern browsers but had problems with old IE11. This should be fixed by the meantime - but could you check with different browsers please?
1. When a person was just "invited" to a fresh meeting series, this cookie sometimes was not set, so the person could "see" the attachment but not download it. Could you please log out of 4Minitz, then "RELOAD" the whole 4Minitz App (CTRL+R), then log in again. From then on navigate to the minutes with attachment, and re-try to download. If still not working try to simply press "CTRL+R" on the minutes page to refresh the page with attachment (without re-login!). Then re-try download.

Please report back what you experience.

**Comment by derwok** [comment]
Ah! And maybe you could check the server side logs if Meteor:Files wants to say something to us?

**Comment by mechanysm** [comment]
Hi Derwok,

I hope i haven't missed anything apologies if I have.

Looks like it might be Chrome and versions of IE after doing testing but here are the answers to your questions.

- Yes we are on version 1.5.2
- No its not in a nice pop up.
- Yes it says "File Not Found :(" in plain text (In chrome)
- Browsers tested
 - Chrome 67 - Not working on multiple computers
 - Firefox 61 - Working
 - Internet explorer 11 - Working 11.112.17134.0, Not working 11.251.16299.0
 - Opera 53 - Working
-No the attachment is still not accessible after performing the refresh procedure you described.

4minitz.log tail, the prohibited messages are only created by Chrome and IE
```
Attachment download prohibited. User not logged in.
Attachment download prohibited. User not logged in.
Attachment download prohibited. User not logged in.
meetingseries.update: undefined
Attachment download prohibited. User not logged in.
```

Hope this helps.
Cheers

**Comment by mechanysm** [comment]
Ok this is weird.

I added in the following as I have been asked to look into the pdf\html generation and now I can download attachments in chrome... why?

This
```
"docGeneration": {
        "enabled": true,
        "format": "html",
        "targetDocPath": "4minitz_storage/protocols"
```
Changed to this
```
"docGeneration": {
        "enabled": true,
        "format": "html",
        "targetDocPath": "4minitz_storage/protocols",
        "pathToWkhtmltopdf": "/usr/local/bin/wkhtmltopdf",
        "wkhtmltopdfParameters": "--no-outline --print-media-type --no-background",
        "pathToGhostscript": "/usr/local/bin/gs",
        "pathToPDFADefinitionFile": "/usr/local/bin/gs/lib/PDFA_def.ps",
        "ICCProfileType" : "cmyk"
```

**Comment by derwok** [comment]
OK - for a weird observation (and this is indeed one!) an even more weird explanation.

The error thrown is of our package Veliov:MeteorFiles.
Maybe this package or one of it's dependecies had a bad internal state somehow.
The change of the settings.json triggers a server side restart. Which will refresh all server side components. Thats why the error went away magically?!

Just a guess.

I will close this issue - please reopen if problem shows up again.
