### ISSUE TITLE
Add attachments to topics or info-items

### ISSUE THREAD

**Issue by miscs** [4minitz/4minitz#463]
Hi all,

just discovered 4minitz - great piece of software, thank you for sharing!

One question regarding attachments: Is it possible to add attachments to topics or info-items? 
If nor, is it somehow possible to create a link from topics or info-items to the attachments added to the Minutes?

Thanks!
Steve

**Comment by derwok** [comment]
Hey Steve,
great you like 4Minitz. Have fun!

To your question: right now it is only possible to add atachments to a minute. We thought this would be sufficient to "find" it later on.

But it is possible to add a link to an already uploaded attachment inside the details(!) section. Because in details section (of an action item or info item) you have mark down support. With markdown you can create links. First grab the attachment URL by right clicking and "copy link location" to you clip board. Then enter into a details editor and just paste the link. It will be clickable afterwards.

**Pro Tip:** 
If the attachment is an image (like JPEG or PNG or SVG), then in a details section you can directly embed the uploaded attachment image like so:
```
![](https://demo.4minitz.com/cdn/storage/AttachmentsCollection/trCNQShAwnT5mitd3/original/trCNQShAwnT5mitd3.png)
```

Just make sure to remove the "?download=true" from the end of the attachment URL
Then the details might look like this:

![grafik](https://user-images.githubusercontent.com/4393698/45799608-6a62ee80-bcae-11e8-859a-87affbd767ce.png)

Disclaimer: embedded images are NOT sent via eMail of the meeting minutes. They will only be visible inside the 4Minitz Web Application iside your browser.

**Comment by miscs** [comment]
Perfect! Thank you for the fast feedback!

**Comment by ojdo** [comment]
After having been in *two separate* meetings now where the meeting coordinator did not find the attachment feature at all, I just wanted to recreate this very feature request.

Background: it seems to be the strong assumption that most attachments belong to *a topic* rather than a meeting. And although power users certainly are capable of creating a Markdown link from a topic to back to a file URL, a more visible way to

  - either "associate" a per-meeting attachment (as it exists currently) to a topic or
  - completely change the structure to per-topic attachments, which then will appear together with its topic

would be very beneficial. The first option seems like the less disruptive, while the second option offers potential for more feature creep 😉
